"""creating a field created_at in useronetimepassword

Revision ID: 0cf8c7803b34
Revises: 3496b8530741
Create Date: 2025-03-18 19:55:24.766241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf8c7803b34'
down_revision: Union[str, None] = '3496b8530741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_one_time_passwords', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_one_time_passwords', 'created_at')
    # ### end Alembic commands ###
