"""creating a detected table

Revision ID: 1c5d794a4f15
Revises: 9aedafb5f475
Create Date: 2025-03-21 15:30:35.577767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5d794a4f15'
down_revision: Union[str, None] = '9aedafb5f475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_panoramics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_panoramic_image', sa.Integer(), nullable=True),
    sa.Column('detected_image_url', sa.String(), nullable=False),
    sa.Column('detected_crop_image_url', sa.String(), nullable=False),
    sa.Column('detection_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_panoramic_image'], ['panoramic_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_panoramics_id'), 'detected_panoramics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detected_panoramics_id'), table_name='detected_panoramics')
    op.drop_table('detected_panoramics')
    # ### end Alembic commands ###
