"""adding uniq value in panoramic table

Revision ID: 646007cded2c
Revises: 1c5d794a4f15
Create Date: 2025-03-24 13:18:30.268719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646007cded2c'
down_revision: Union[str, None] = '1c5d794a4f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'panoramic_images', ['no_rm'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'panoramic_images', type_='unique')
    # ### end Alembic commands ###
