"""fixing table panoramic

Revision ID: 9aedafb5f475
Revises: a20af6224153
Create Date: 2025-03-21 14:17:51.163593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aedafb5f475'
down_revision: Union[str, None] = 'a20af6224153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panoramic_images', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('panoramic_images_no_rm_key', 'panoramic_images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('panoramic_images_no_rm_key', 'panoramic_images', ['no_rm'])
    op.alter_column('panoramic_images', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
