"""creating name

Revision ID: b6b21e1c01ff
Revises: 646007cded2c
Create Date: 2025-03-25 00:47:49.815586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b21e1c01ff'
down_revision: Union[str, None] = '646007cded2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panoramic_images', sa.Column('name_patient', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panoramic_images', 'name_patient')
    # ### end Alembic commands ###
