"""editing detected table

Revision ID: e93083c185f5
Revises: b6b21e1c01ff
Create Date: 2025-04-04 17:39:47.366121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e93083c185f5'
down_revision: Union[str, None] = 'b6b21e1c01ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detected_panoramics', sa.Column('result_detection_images', sa.JSON(), nullable=False))
    op.drop_column('detected_panoramics', 'detection_result')
    op.drop_column('detected_panoramics', 'detected_crop_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detected_panoramics', sa.Column('detected_crop_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('detected_panoramics', sa.Column('detection_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('detected_panoramics', 'result_detection_images')
    # ### end Alembic commands ###
